make top-level compose directories only once
If we run a compose with more than one distro, the second distro will
fail because the first one has already created the top-level
directories.

  File "bin/rhcephcompose", line 6, in <module>
    main.RHCephCompose()
  File "rhcephcompose/main.py", line 24, in __init__
    compose.run()
  File "rhcephcompose/compose.py", line 95, in run
    self.run_distro(distro)
  File "rhcephcompose/compose.py", line 125, in run_distro
    os.mkdir(self.output_dir)
  OSError: [Errno 17] File exists: 'trees/Ceph-2-Ubuntu-x86_64-20160429.t.0'

Rather than creating the top-level directories each time the
run_distro() method is called, create them just once, in run().